server:
  port: 8080

spring:
  jpa:
    open-in-view: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: none
    properties:
      show-sql: false
      hibernate:
        format_sql: true
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: ''
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: 'true'
      path: /h2-console

management:
  trace:
    http:
      enabled: true
logging:
  level:
    org:
      hibernate:
        SQL: info